Kan
kanroot/Experiencia1_Castillo_Riquelme_Sandoval pull request #10
Opened 2021-04-07 01:46 UTC by kanroot

Varios, ver los commits.

2021-04-07 17:23 UTC, corp-0 requested changes

2021-04-07 17:23 UTC, corp-0 commented on Index.html
> +                                    <button class='btn green'>Unete</button>
```suggestion
                                    <button class='btn green'>Únete</button>
```

2021-04-07 17:23 UTC, corp-0 commented on Index.html
> +                                    <button class='btn green'>Unete</button>
```suggestion
                                    <button class='btn green'>Únete</button>
```

2021-04-07 17:23 UTC, corp-0 commented on Index.html
> +                            <strong>*Cada pin representa a un unico usuario.</strong>
```suggestion
                            <small>*Cada pin representa a un único usuario.</small>
```

2021-04-07 17:23 UTC, corp-0 commented on Index.html
> +                                    <button class='btn green'>Unete</button>
```suggestion
                                    <button class='btn green'>Únete</button>
```

2021-04-07 17:24 UTC, corp-0 commented
Podrías squashear un par de commits

2021-04-08 21:45 UTC, kanroot commented
> Podrías squashear un par de commits
> No se como squashea xd

2021-04-08 21:49 UTC, corp-0 commented
después de la prueba de inglés te puedo explicar

2021-04-08 22:08 UTC, kanroot commented
> después de la prueba de inglés te puedo explicar

ya, me avisas

2021-04-11 07:36 UTC, corp-0 commented
acuérdame el domingo pa que mergiemos esto

2021-04-11 20:49 UTC, corp-0 approved these changes

2021-04-11 20:54 UTC, merged